# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwimmingCompetition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'TextFieldEffects'

  # Pods for SwimmingCompetition
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'SwiftyJSON'
    pod 'Alamofire'


  target 'SwimmingCompetitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwimmingCompetitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
