# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwimmingCompetition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwimmingCompetition
    pod 'Firebase/Core'
    pod 'Firebase/Auth'

  target 'SwimmingCompetitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwimmingCompetitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
